export const gigaChips = [
  {
    number: 2,
    image: "../../assets/giga/MMBN3GChip02.jpg",
    name: "BassGS",
    type: "",
    damage: "700",
    lettercode: "X",
    memory: 99,
    description: "Bass' secret weapon",
    key: "BassGSX",
    chipType: "giga",
    count: 0,
  },
  {
    number: 6,
    image: "../../assets/giga/MMBN3GChip06.jpg",
    name: "GutsManV5",
    type: "",
    damage: "120",
    lettercode: "G",
    memory: 79,
    description: "Sneaks up to smash panels!",
    key: "GutsManV5G",
    chipType: "giga",
    count: 0,
  },
  {
    number: 7,
    image: "../../assets/giga/MMBN3GChip07.jpg",
    name: "ProtoMnV5",
    type: "",
    damage: "240",
    lettercode: "B",
    memory: 98,
    description: "Moves in to slice the enemy",
    key: "ProtoMnV5B",
    chipType: "giga",
    count: 0,
  },
  {
    number: 8,
    image: "../../assets/giga/MMBN3GChip08.jpg",
    name: "FlashMnV5",
    type: "",
    damage: "150",
    lettercode: "F",
    memory: 89,
    description: "Flash atk paralyzes enemy",
    key: "FlashMnV5F",
    chipType: "giga",
    count: 0,
  },
  {
    number: 9,
    image: "../../assets/giga/MMBN3GChip09.jpg",
    name: "BeastMnV5",
    type: "",
    damage: "80",
    lettercode: "B",
    memory: 84,
    description: "Claw atk 3 squares ahead!",
    key: "BeastMnV5B",
    chipType: "giga",
    count: 0,
  },
  {
    number: 10,
    image: "",
    name: "BubblMnV5",
    type: "",
    damage: "20",
    lettercode: "B",
    memory: 86,
    description: "Fires several AquaShots",
    key: "BubblMnV5B",
    chipType: "giga",
    count: 0,
  },
  {
    number: 11,
    image: "",
    name: "DesrtMnV5",
    type: "",
    damage: "210",
    lettercode: "D",
    memory: 80,
    description: "Launches fists at enemies!",
    key: "DesrtMnV5D",
    chipType: "giga",
    count: 0,
  },
  {
    number: 12,
    image: "",
    name: "PlantMnV5",
    type: "",
    damage: "60",
    lettercode: "P",
    memory: 80,
    description: "Vines harm all enemies!",
    key: "PlantMnV5P",
    chipType: "giga",
    count: 0,
  },
  {
    number: 13,
    image: "",
    name: "FlamManV5",
    type: "",
    damage: "240",
    lettercode: "F",
    memory: 82,
    description: "Flames burn all enemies!",
    key: "FlamManV5F",
    chipType: "giga",
    count: 0,
  },
  {
    number: 14,
    image: "",
    name: "DrillMnV5",
    type: "",
    damage: "150",
    lettercode: "D",
    memory: 82,
    description: "3 drills fly at enemies!",
    key: "DrillMnV5D",
    chipType: "giga",
    count: 0,
  },
  {
    number: 15,
    image: "",
    name: "MetalMnV5",
    type: "",
    damage: "250",
    lettercode: "M",
    memory: 90,
    description: "Iron fist smashes 1 square!",
    key: "MetalMnV5M",
    chipType: "giga",
    count: 0,
  },
  {
    number: 16,
    image: "",
    name: "KingManV5",
    type: "",
    damage: "280",
    lettercode: "K",
    memory: 84,
    description: "Move up 3 square & 4-way hit",
    key: "KingManV5K",
    chipType: "giga",
    count: 0,
  },
  {
    number: 17,
    image: "",
    name: "MistManV5",
    type: "",
    damage: "170",
    lettercode: "M",
    memory: 80,
    description: "Appears from mist & attacks",
    key: "MistManV5M",
    chipType: "giga",
    count: 0,
  },
  {
    number: 18,
    image: "",
    name: "BowlManV5",
    type: "",
    damage: "180",
    lettercode: "B",
    memory: 88,
    description: "Lines up pins for a strike!",
    key: "BowlManV5B",
    chipType: "giga",
    count: 0,
  },
  {
    number: 19,
    image: "",
    name: "DarkManV5",
    type: "",
    damage: "30",
    lettercode: "D",
    memory: 88,
    description: "Creates 3 caves in enmy area",
    key: "DarkManV5D",
    chipType: "giga",
    count: 0,
  },
  {
    number: 20,
    image: "",
    name: "JapanMnV5",
    type: "",
    damage: "60",
    lettercode: "Y",
    memory: 94,
    description: "Multiple attacks w/ spear",
    key: "JapanMnV5Y",
    chipType: "giga",
    count: 0,
  },
  {
    number: 1,
    image: "",
    name: "NavRcycl",
    type: "",
    damage: "-",
    lettercode: "*",
    memory: 50,
    description: "Recalls last Navi used",
    key: "NavRcycl*",
    chipType: "giga",
    count: 0,
  },
  {
    number: 2,
    image: "",
    name: "Bass",
    type: "",
    damage: "90",
    lettercode: "X",
    memory: 98,
    description: "Dark chip Explodes for 3 sq",
    key: "BassX",
    chipType: "giga",
    count: 0,
  },
  {
    number: 3,
    image: "",
    name: "Serenade",
    type: "",
    damage: "100",
    lettercode: "S",
    memory: 97,
    description: "Dark chip Holy pwr to front",
    key: "SerenadeS",
    chipType: "giga",
    count: 0,
  },
  {
    number: 4,
    image: "",
    name: "Balance",
    type: "",
    damage: "-",
    lettercode: "Y",
    memory: 60,
    description: "Both HP reduced by half!",
    key: "BalanceY",
    chipType: "giga",
    count: 0,
  },
  {
    number: 5,
    image: "",
    name: "AlphArmΣ",
    type: "",
    damage: "50",
    lettercode: "V",
    memory: 97,
    description: "3-stage electric attack!",
    key: "AlphArmΣV",
    chipType: "giga",
    count: 0,
  },
  {
    number: 1,
    image: "",
    name: "FoldrBak",
    type: "",
    damage: "-",
    lettercode: "*",
    memory: 99,
    description: "Restores all chips & folders",
    key: "FoldrBak*",
    chipType: "giga",
    count: 0,
  },
  {
    number: 2,
    image: "",
    name: "Bass+",
    type: "",
    damage: "550",
    lettercode: "X",
    memory: 98,
    description: "Dark chip Smashes panels!",
    key: "Bass+X",
    chipType: "giga",
    count: 0,
  },
  {
    number: 3,
    image: "",
    name: "DarkAura",
    type: "",
    damage: "-",
    lettercode: "A",
    memory: 55,
    description: "Dark chip repels <300 atks",
    key: "DarkAuraA",
    chipType: "giga",
    count: 0,
  },
  {
    number: 4,
    image: "",
    name: "DeltaRay",
    type: "",
    damage: "220",
    lettercode: "Z",
    memory: 92,
    description: "Use A btn for up to 3 attacks",
    key: "DeltaRayZ",
    chipType: "giga",
    count: 0,
  },
  {
    number: 5,
    image: "",
    name: "AlphArmΩ",
    type: "",
    damage: "500",
    lettercode: "V",
    memory: 97,
    description: "Launches a giant rocket!",
    key: "AlphArmΩV",
    chipType: "giga",
    count: 0,
  },
];
