export const gigaChips = [
  {
    number: 2,
    image: "../../assets/giga/MMBN3GChip02.jpg",
    name: "BassGS",
    type: "",
    damage: "700",
    lettercode: "X",
    memory: 99,
    description: "Bass' secret weapon",
    key: "clk9g3vd00000bx1ee7baasol",
    chipType: "giga",
    count: 0,
  },
  {
    number: 6,
    image: "../../assets/giga/MMBN3GChip06.jpg",
    name: "GutsManV5",
    type: "",
    damage: "120",
    lettercode: "G",
    memory: 79,
    description: "Sneaks up to smash panels!",
    key: "clk9g3vd10001bx1ehzfwfcbs",
    chipType: "giga",
    count: 0,
  },
  {
    number: 7,
    image: "../../assets/giga/MMBN3GChip07.jpg",
    name: "ProtoMnV5",
    type: "",
    damage: "240",
    lettercode: "B",
    memory: 98,
    description: "Moves in to slice the enemy",
    key: "clk9g3vd10002bx1edhdsb3km",
    chipType: "giga",
    count: 0,
  },
  {
    number: 8,
    image: "../../assets/giga/MMBN3GChip08.jpg",
    name: "FlashMnV5",
    type: "",
    damage: "150",
    lettercode: "F",
    memory: 89,
    description: "Flash atk paralyzes enemy",
    key: "clk9g3vd10003bx1e5wrnhogt",
    chipType: "giga",
    count: 0,
  },
  {
    number: 9,
    image: "../../assets/giga/MMBN3GChip09.jpg",
    name: "BeastMnV5",
    type: "",
    damage: "80",
    lettercode: "B",
    memory: 84,
    description: "Claw atk 3 squares ahead!",
    key: "clk9g3vd10004bx1ebwjp2jeg",
    chipType: "giga",
    count: 0,
  },
  {
    number: 10,
    image: "../../assets/giga/MMBN3GChip10.jpg",
    name: "BubblMnV5",
    type: "",
    damage: "20",
    lettercode: "B",
    memory: 86,
    description: "Fires several AquaShots",
    key: "clk9g3vd10005bx1ed0n7dpnn",
    chipType: "giga",
    count: 0,
  },
  {
    number: 11,
    image: "../../assets/giga/MMBN3GChip11.jpg",
    name: "DesrtMnV5",
    type: "",
    damage: "210",
    lettercode: "D",
    memory: 80,
    description: "Launches fists at enemies!",
    key: "clk9g3vd10006bx1ec9c69wae",
    chipType: "giga",
    count: 0,
  },
  {
    number: 12,
    image: "../../assets/giga/MMBN3GChip12.jpg",
    name: "PlantMnV5",
    type: "",
    damage: "60",
    lettercode: "P",
    memory: 80,
    description: "Vines harm all enemies!",
    key: "clk9g3vd10007bx1e9tcohwy1",
    chipType: "giga",
    count: 0,
  },
  {
    number: 13,
    image: "../../assets/giga/MMBN3GChip13.jpg",
    name: "FlamManV5",
    type: "",
    damage: "240",
    lettercode: "F",
    memory: 82,
    description: "Flames burn all enemies!",
    key: "clk9g3vd10008bx1ebj4b4gc1",
    chipType: "giga",
    count: 0,
  },
  {
    number: 14,
    image: "../../assets/giga/MMBN3GChip14.jpg",
    name: "DrillMnV5",
    type: "",
    damage: "150",
    lettercode: "D",
    memory: 82,
    description: "3 drills fly at enemies!",
    key: "clk9g3vd10009bx1e7sry5bv7",
    chipType: "giga",
    count: 0,
  },
  {
    number: 15,
    image: "../../assets/giga/MMBN3GChip15.jpg",
    name: "MetalMnV5",
    type: "",
    damage: "250",
    lettercode: "M",
    memory: 90,
    description: "Iron fist smashes 1 square!",
    key: "clk9g3vd1000abx1e9g8u74x8",
    chipType: "giga",
    count: 0,
  },
  {
    number: 16,
    image: "../../assets/giga/MMBN3GChip16.jpg",
    name: "KingManV5",
    type: "",
    damage: "280",
    lettercode: "K",
    memory: 84,
    description: "Move up 3 square & 4-way hit",
    key: "clk9g3vd2000bbx1eavpj6v0v",
    chipType: "giga",
    count: 0,
  },
  {
    number: 17,
    image: "../../assets/giga/MMBN3GChip17.jpg",
    name: "MistManV5",
    type: "",
    damage: "170",
    lettercode: "M",
    memory: 80,
    description: "Appears from mist & attacks",
    key: "clk9g3vd2000cbx1ebt7jh4va",
    chipType: "giga",
    count: 0,
  },
  {
    number: 18,
    image: "../../assets/giga/MMBN3GChip18.jpg",
    name: "BowlManV5",
    type: "",
    damage: "180",
    lettercode: "B",
    memory: 88,
    description: "Lines up pins for a strike!",
    key: "clk9g3vd2000dbx1ehalg3t3x",
    chipType: "giga",
    count: 0,
  },
  {
    number: 19,
    image: "../../assets/giga/MMBN3GChip19.jpg",
    name: "DarkManV5",
    type: "",
    damage: "30",
    lettercode: "D",
    memory: 88,
    description: "Creates 3 caves in enmy area",
    key: "clk9g3vd2000ebx1e1s683bai",
    chipType: "giga",
    count: 0,
  },
  {
    number: 20,
    image: "../../assets/giga/MMBN3GChip20.jpg",
    name: "JapanMnV5",
    type: "",
    damage: "60",
    lettercode: "Y",
    memory: 94,
    description: "Multiple attacks w/ spear",
    key: "clk9g3vd2000fbx1e7d7e6mcf",
    chipType: "giga",
    count: 0,
  },
  {
    number: 1,
    image: "../../assets/giga/MMBN3GChip01W.jpg",
    name: "NavRcycl",
    type: "",
    damage: "-",
    lettercode: "*",
    memory: 50,
    description: "Recalls last Navi used",
    key: "clk9g3vd2000gbx1eeltc8v35",
    chipType: "giga",
    count: 0,
  },
  {
    number: 2,
    image: "../../assets/giga/MMBN3GChip02W.jpg",
    name: "Bass",
    type: "",
    damage: "90",
    lettercode: "X",
    memory: 98,
    description: "Dark chip Explodes for 3 sq",
    key: "clk9g3vd2000hbx1e35h7cmpv",
    chipType: "giga",
    count: 0,
  },
  {
    number: 3,
    image: "../../assets/giga/MMBN3GChip03W.jpg",
    name: "Serenade",
    type: "",
    damage: "100",
    lettercode: "S",
    memory: 97,
    description: "Dark chip Holy pwr to front",
    key: "clk9g3vd2000ibx1e0di17yek",
    chipType: "giga",
    count: 0,
  },
  {
    number: 4,
    image: "../../assets/giga/MMBN3GChip04W.jpg",
    name: "Balance",
    type: "",
    damage: "-",
    lettercode: "Y",
    memory: 60,
    description: "Both HP reduced by half!",
    key: "clk9g3vd2000jbx1e36bu4vq7",
    chipType: "giga",
    count: 0,
  },
  {
    number: 5,
    image: "../../assets/giga/MMBN3GChip05W.jpg",
    name: "AlphArmΣ",
    type: "",
    damage: "50",
    lettercode: "V",
    memory: 97,
    description: "3-stage electric attack!",
    key: "clk9g3vd2000kbx1e9ryi6p1r",
    chipType: "giga",
    count: 0,
  },
  {
    number: 1,
    image: "../../assets/giga/MMBN3GChip01B.jpg",
    name: "FoldrBak",
    type: "",
    damage: "-",
    lettercode: "*",
    memory: 99,
    description: "Restores all chips & folders",
    key: "clk9g3vd2000lbx1ea2zs8fki",
    chipType: "giga",
    count: 0,
  },
  {
    number: 2,
    image: "../../assets/giga/MMBN3GChip02B.jpg",
    name: "Bass+",
    type: "",
    damage: "550",
    lettercode: "X",
    memory: 98,
    description: "Dark chip Smashes panels!",
    key: "clk9g3vd2000mbx1egjx8bx8d",
    chipType: "giga",
    count: 0,
  },
  {
    number: 3,
    image: "../../assets/giga/MMBN3GChip03B.jpg",
    name: "DarkAura",
    type: "",
    damage: "-",
    lettercode: "A",
    memory: 55,
    description: "Dark chip repels <300 atks",
    key: "clk9g3vd2000nbx1eeo4x201g",
    chipType: "giga",
    count: 0,
  },
  {
    number: 4,
    image: "../../assets/giga/MMBN3GChip04B.jpg",
    name: "DeltaRay",
    type: "",
    damage: "220",
    lettercode: "Z",
    memory: 92,
    description: "Use A btn for up to 3 attacks",
    key: "clk9g3vd2000obx1e5ya6bva6",
    chipType: "giga",
    count: 0,
  },
  {
    number: 5,
    image: "../../assets/giga/MMBN3GChip05B.jpg",
    name: "AlphArmΩ",
    type: "",
    damage: "500",
    lettercode: "V",
    memory: 97,
    description: "Launches a giant rocket!",
    key: "clk9g3vd2000pbx1ef7s70fyx",
    chipType: "giga",
    count: 0,
  },
];
