export const megaChips = [
  {
    number: 1,
    image: "",
    name: "Muramasa",
    type: "",
    damage: "????",
    lettercode: "M",
    memory: "74 MB",
    description: "Power=amount of HP lost!",
    key: "MuramasaM",
    chipType: "giga",
  },
  {
    number: 2,
    image: "",
    name: "HeroSwrd",
    type: "",
    damage: "180",
    lettercode: "P",
    memory: "65 MB",
    description: "Legendary swrd cuts 3 sq!",
    key: "HeroSwrdP",
    chipType: "giga",
  },
  {
    number: 3,
    image: "",
    name: "ZeusHamr",
    type: "",
    damage: "250",
    lettercode: "Z",
    memory: "90 MB",
    description: "Damages anyone on a panel",
    key: "ZeusHamrZ",
    chipType: "giga",
  },
  {
    number: 4,
    image: "",
    name: "StandOut",
    type: "",
    damage: "220",
    lettercode: "P",
    memory: "22 MB",
    description: "Send Fire into hole",
    key: "StandOutP",
    chipType: "giga",
  },
  {
    number: 5,
    image: "",
    name: "Salamndr",
    type: "",
    damage: "300",
    lettercode: "S",
    memory: "50 MB",
    description: "Send Fire into hole",
    key: "SalamndrS",
    chipType: "giga",
  },
  {
    number: 5,
    image: "",
    name: "Salamndr",
    type: "",
    damage: "300",
    lettercode: "*",
    memory: "50 MB",
    description: "Send Fire into hole",
    key: "Salamndr*",
    chipType: "giga",
  },
  {
    number: 6,
    image: "",
    name: "WatrLine",
    type: "",
    damage: "180",
    lettercode: "C",
    memory: "18 MB",
    description: "Draw wter from hole",
    key: "WatrLineC",
    chipType: "giga",
  },
  {
    number: 6,
    image: "",
    name: "WatrLine",
    type: "",
    damage: "180",
    lettercode: "*",
    memory: "18 MB",
    description: "Draw wter from hole",
    key: "WatrLine*",
    chipType: "giga",
  },
  {
    number: 7,
    image: "",
    name: "Fountain",
    type: "",
    damage: "240",
    lettercode: "D",
    memory: "48 MB",
    description: "Draw wter from hole",
    key: "FountainD",
    chipType: "giga",
  },
  {
    number: 7,
    image: "",
    name: "Fountain",
    type: "",
    damage: "240",
    lettercode: "*",
    memory: "48 MB",
    description: "Draw wter from hole",
    key: "Fountain*",
    chipType: "giga",
  },
  {
    number: 8,
    image: "",
    name: "Lightning",
    type: "",
    damage: "160",
    lettercode: "L",
    memory: "30 MB",
    description: "Dmgs object & area",
    key: "LightningL",
    chipType: "giga",
  },
  {
    number: 8,
    image: "",
    name: "Lightning",
    type: "",
    damage: "160",
    lettercode: "*",
    memory: "30 MB",
    description: "Dmgs object & area",
    key: "Lightning*",
    chipType: "giga",
  },
  {
    number: 9,
    image: "",
    name: "Bolt",
    type: "",
    damage: "210",
    lettercode: "T",
    memory: "52 MB",
    description: "Dmgs object & area",
    key: "BoltT",
    chipType: "giga",
  },
  {
    number: 9,
    image: "",
    name: "Bolt",
    type: "",
    damage: "210",
    lettercode: "*",
    memory: "52 MB",
    description: "Dmgs object & area",
    key: "Bolt*",
    chipType: "giga",
  },
  {
    number: 10,
    image: "",
    name: "GaiaSwrd",
    type: "",
    damage: "100",
    lettercode: "G",
    memory: "28 MB",
    description: "Take power frm next chip",
    key: "GaiaSwrdG",
    chipType: "giga",
  },
  {
    number: 10,
    image: "",
    name: "GaiaSwrd",
    type: "",
    damage: "100",
    lettercode: "*",
    memory: "28 MB",
    description: "Take power frm next chip",
    key: "GaiaSwrd*",
    chipType: "giga",
  },
  {
    number: 11,
    image: "",
    name: "GaiaBlad",
    type: "",
    damage: "100",
    lettercode: "G",
    memory: "55 MB",
    description: "Take power fr. next chip",
    key: "GaiaBladG",
    chipType: "giga",
  },
  {
    number: 11,
    image: "",
    name: "GaiaBlad",
    type: "",
    damage: "100",
    lettercode: "*",
    memory: "55 MB",
    description: "Take power fr. next chip",
    key: "GaiaBlad*",
    chipType: "giga",
  },
  {
    number: 12,
    image: "",
    name: "Meteors",
    type: "",
    damage: "40",
    lettercode: "R",
    memory: "86 MB",
    description: "Drop many meteors on enemy",
    key: "MeteorsR",
    chipType: "giga",
  },
  {
    number: 13,
    image: "",
    name: "Guardian",
    type: "",
    damage: "-",
    lettercode: "O",
    memory: "82 MB",
    description: "Statue punishes when hit",
    key: "GuardianO",
    chipType: "giga",
  },
  {
    number: 14,
    image: "",
    name: "Anubis",
    type: "",
    damage: "-",
    lettercode: "A",
    memory: "90 MB",
    description: "Anubis poisons enemies",
    key: "AnubisA",
    chipType: "giga",
  },
  {
    number: 15,
    image: "",
    name: "GodStone",
    type: "",
    damage: "150",
    lettercode: "S",
    memory: "66 MB",
    description: "Summons a GodStone from hole",
    key: "GodStoneS",
    chipType: "giga",
  },
  {
    number: 16,
    image: "",
    name: "OldWood",
    type: "",
    damage: "100",
    lettercode: "W",
    memory: "72 MB",
    description: "Summons OldWood from hole",
    key: "OldWoodW",
    chipType: "giga",
  },
  {
    number: 17,
    image: "",
    name: "Jealousy",
    type: "",
    damage: "100",
    lettercode: "J",
    memory: "64 MB",
    description: "More dmg if enemy has chips",
    key: "JealousyJ",
    chipType: "giga",
  },
  {
    number: 18,
    image: "",
    name: "Poltrgst",
    type: "",
    damage: "-",
    lettercode: "G",
    memory: "58 MB",
    description: "Objects thrown at enemies!",
    key: "PoltrgstG",
    chipType: "giga",
  },
  {
    number: 19,
    image: "",
    name: "LifeAura",
    type: "",
    damage: "-",
    lettercode: "D",
    memory: "77 MB",
    description: "Repel all attacks under 200",
    key: "LifeAuraD",
    chipType: "giga",
  },
  {
    number: 20,
    image: "",
    name: "FullCust",
    type: "",
    damage: "-",
    lettercode: "*",
    memory: "10 MB",
    description: "CustGauge instantly refills!",
    key: "FullCust*",
    chipType: "giga",
  },
  {
    number: 21,
    image: "",
    name: "Atk+30",
    type: "",
    damage: "-",
    lettercode: "*",
    memory: "50 MB",
    description: "+30 for selected atk chip",
    key: "Atk+30*",
    chipType: "giga",
  },
  {
    number: 22,
    image: "",
    name: "Navi+40",
    type: "",
    damage: "-",
    lettercode: "*",
    memory: "60 MB",
    description: "+40 for selected Navi chip",
    key: "Navi+40*",
    chipType: "giga",
  },
  {
    number: 23,
    image: "",
    name: "Roll",
    type: "",
    damage: "20",
    lettercode: "R",
    memory: "10 MB",
    description: "Attack an enemy, heal you",
    key: "RollR",
    chipType: "giga",
  },
  {
    number: 24,
    image: "",
    name: "Roll V2",
    type: "",
    damage: "30",
    lettercode: "R",
    memory: "22 MB",
    description: "Attack an enemy, heal you",
    key: "Roll V2R",
    chipType: "giga",
  },
  {
    number: 25,
    image: "",
    name: "Roll V3",
    type: "",
    damage: "40",
    lettercode: "R",
    memory: "34 MB",
    description: "Attack an enemy, heal you",
    key: "Roll V3R",
    chipType: "giga",
  },
  {
    number: 26,
    image: "",
    name: "GutsMan",
    type: "",
    damage: "50",
    lettercode: "G",
    memory: "15 MB",
    description: "Sneaks up to smash panels!",
    key: "GutsManG",
    chipType: "giga",
  },
  {
    number: 27,
    image: "",
    name: "GutsMan V2",
    type: "",
    damage: "70",
    lettercode: "G",
    memory: "41 MB",
    description: "Sneaks up to smash panels!",
    key: "GutsMan V2G",
    chipType: "giga",
  },
  {
    number: 28,
    image: "",
    name: "GutsMan V3",
    type: "",
    damage: "90",
    lettercode: "G",
    memory: "57 MB",
    description: "Sneaks up to smash panels!",
    key: "GutsMan V3G",
    chipType: "giga",
  },
  {
    number: 29,
    image: "",
    name: "GutsMan V4",
    type: "",
    damage: "100",
    lettercode: "G",
    memory: "63 MB",
    description: "Sneaks up to smash panels!",
    key: "GutsMan V4G",
    chipType: "giga",
  },
  {
    number: 30,
    image: "",
    name: "ProtoMan",
    type: "",
    damage: "160",
    lettercode: "B",
    memory: "68 MB",
    description: "Moves in to slice the enemy",
    key: "ProtoManB",
    chipType: "giga",
  },
  {
    number: 31,
    image: "",
    name: "ProtoMn V2",
    type: "",
    damage: "180",
    lettercode: "B",
    memory: "76 MB",
    description: "Moves in to slice the enemy",
    key: "ProtoMn V2B",
    chipType: "giga",
  },
  {
    number: 32,
    image: "",
    name: "ProtoMn V3",
    type: "",
    damage: "200",
    lettercode: "B",
    memory: "82 MB",
    description: "Moves in to slice the enemy",
    key: "ProtoMn V3B",
    chipType: "giga",
  },
  {
    number: 33,
    image: "",
    name: "ProtoMn V4",
    type: "",
    damage: "220",
    lettercode: "B",
    memory: "90 MB",
    description: "Moves in to slice the enemy",
    key: "ProtoMn V4B",
    chipType: "giga",
  },
  {
    number: 34,
    image: "",
    name: "FlashMan",
    type: "",
    damage: "50",
    lettercode: "F",
    memory: "39 MB",
    description: "Flash atk paralyzes enemy",
    key: "FlashManF",
    chipType: "giga",
  },
  {
    number: 35,
    image: "",
    name: "FlashMn V2",
    type: "",
    damage: "70",
    lettercode: "F",
    memory: "59 MB",
    description: "Flash atk paralyzes enemy",
    key: "FlashMn V2F",
    chipType: "giga",
  },
  {
    number: 36,
    image: "",
    name: "FlashMn V3",
    type: "",
    damage: "90",
    lettercode: "F",
    memory: "69 MB",
    description: "Flash atk paralyzes enemy",
    key: "FlashMn V3F",
    chipType: "giga",
  },
  {
    number: 37,
    image: "",
    name: "FlashMn V4",
    type: "",
    damage: "120",
    lettercode: "F",
    memory: "79 MB",
    description: "Flash atk paralyzes enemy",
    key: "FlashMn V4F",
    chipType: "giga",
  },
  {
    number: 38,
    image: "",
    name: "BeastMan",
    type: "",
    damage: "40",
    lettercode: "B",
    memory: "38 MB",
    description: "Claw atk 3 squares ahead!",
    key: "BeastManB",
    chipType: "giga",
  },
  {
    number: 39,
    image: "",
    name: "BeastMn V2",
    type: "",
    damage: "50",
    lettercode: "B",
    memory: "60 MB",
    description: "Claw atk 3 squares ahead!",
    key: "BeastMn V2B",
    chipType: "giga",
  },
  {
    number: 40,
    image: "",
    name: "BeastMn V3",
    type: "",
    damage: "60",
    lettercode: "B",
    memory: "68 MB",
    description: "Claw atk 3 squares ahead!",
    key: "BeastMn V3B",
    chipType: "giga",
  },
  {
    number: 41,
    image: "",
    name: "BeastMn V4",
    type: "",
    damage: "70",
    lettercode: "B",
    memory: "76 MB",
    description: "Claw atk 3 squares ahead!",
    key: "BeastMn V4B",
    chipType: "giga",
  },
  {
    number: 42,
    image: "",
    name: "BubblMan",
    type: "",
    damage: "20",
    lettercode: "B",
    memory: "50 MB",
    description: "Fires several AquaShots",
    key: "BubblManB",
    chipType: "giga",
  },
  {
    number: 43,
    image: "",
    name: "BubblMn V2",
    type: "",
    damage: "20",
    lettercode: "B",
    memory: "62 MB",
    description: "Fires several AquaShots",
    key: "BubblMn V2B",
    chipType: "giga",
  },
  {
    number: 44,
    image: "",
    name: "BubblMn V3",
    type: "",
    damage: "20",
    lettercode: "B",
    memory: "74 MB",
    description: "Fires several AquaShots",
    key: "BubblMn V3B",
    chipType: "giga",
  },
  {
    number: 45,
    image: "",
    name: "BubblMn V4",
    type: "",
    damage: "20",
    lettercode: "B",
    memory: "80 MB",
    description: "Fires several AquaShots",
    key: "BubblMn V4B",
    chipType: "giga",
  },
  {
    number: 46,
    image: "",
    name: "DesrtMan",
    type: "",
    damage: "120",
    lettercode: "D",
    memory: "38 MB",
    description: "Launches fists at enemies!",
    key: "DesrtManD",
    chipType: "giga",
  },
  {
    number: 47,
    image: "",
    name: "DesrtMn V2",
    type: "",
    damage: "140",
    lettercode: "D",
    memory: "52 MB",
    description: "Launches fists at enemies!",
    key: "DesrtMn V2D",
    chipType: "giga",
  },
  {
    number: 48,
    image: "",
    name: "DesrtMn V3",
    type: "",
    damage: "160",
    lettercode: "D",
    memory: "64 MB",
    description: "Launches fists at enemies!",
    key: "DesrtMn V3D",
    chipType: "giga",
  },
  {
    number: 49,
    image: "",
    name: "DesrtMn V4",
    type: "",
    damage: "180",
    lettercode: "D",
    memory: "72 MB",
    description: "Launches fists at enemies!",
    key: "DesrtMn V4D",
    chipType: "giga",
  },
  {
    number: 50,
    image: "",
    name: "PlantMan",
    type: "",
    damage: "20",
    lettercode: "P",
    memory: "60 MB",
    description: "Vines harm all enemies!",
    key: "PlantManP",
    chipType: "giga",
  },
  {
    number: 51,
    image: "",
    name: "PlantMn V2",
    type: "",
    damage: "30",
    lettercode: "P",
    memory: "65 MB",
    description: "Vines harm all enemies!",
    key: "PlantMn V2P",
    chipType: "giga",
  },
  {
    number: 52,
    image: "",
    name: "PlantMn V3",
    type: "",
    damage: "40",
    lettercode: "P",
    memory: "70 MB",
    description: "Vines harm all enemies!",
    key: "PlantMn V3P",
    chipType: "giga",
  },
  {
    number: 53,
    image: "",
    name: "PlantMn V4",
    type: "",
    damage: "50",
    lettercode: "P",
    memory: "75 MB",
    description: "Vines harm all enemies!",
    key: "PlantMn V4P",
    chipType: "giga",
  },
  {
    number: 54,
    image: "",
    name: "FlamMan",
    type: "",
    damage: "120",
    lettercode: "F",
    memory: "32 MB",
    description: "Flames burn all enemies!",
    key: "FlamManF",
    chipType: "giga",
  },
  {
    number: 55,
    image: "",
    name: "FlamMan V2",
    type: "",
    damage: "150",
    lettercode: "F",
    memory: "52 MB",
    description: "Flames burn all enemies!",
    key: "FlamMan V2F",
    chipType: "giga",
  },
  {
    number: 56,
    image: "",
    name: "FlamMan V3",
    type: "",
    damage: "180",
    lettercode: "F",
    memory: "62 MB",
    description: "Flames burn all enemies!",
    key: "FlamMan V3F",
    chipType: "giga",
  },
  {
    number: 57,
    image: "",
    name: "FlamMan V4",
    type: "",
    damage: "210",
    lettercode: "F",
    memory: "72 MB",
    description: "Flames burn all enemies!",
    key: "FlamMan V4F",
    chipType: "giga",
  },
  {
    number: 58,
    image: "",
    name: "DrillMan",
    type: "",
    damage: "70",
    lettercode: "D",
    memory: "66 MB",
    description: "3 drills fly at enemies!",
    key: "DrillManD",
    chipType: "giga",
  },
  {
    number: 59,
    image: "",
    name: "DrillMn V2",
    type: "",
    damage: "90",
    lettercode: "D",
    memory: "70 MB",
    description: "3 drills fly at enemies!",
    key: "DrillMn V2D",
    chipType: "giga",
  },
  {
    number: 60,
    image: "",
    name: "DrillMn V3",
    type: "",
    damage: "110",
    lettercode: "D",
    memory: "74 MB",
    description: "3 drills fly at enemies!",
    key: "DrillMn V3D",
    chipType: "giga",
  },
  {
    number: 61,
    image: "",
    name: "DrillMn V4",
    type: "",
    damage: "130",
    lettercode: "D",
    memory: "78 MB",
    description: "3 drills fly at enemies!",
    key: "DrillMn V4D",
    chipType: "giga",
  },
  {
    number: 62,
    image: "",
    name: "MetalMan",
    type: "",
    damage: "100",
    lettercode: "M",
    memory: "40 MB",
    description: "Iron fist smashes 1 square!",
    key: "MetalManM",
    chipType: "giga",
  },
  {
    number: 63,
    image: "",
    name: "MetalMn V2",
    type: "",
    damage: "130",
    lettercode: "M",
    memory: "60 MB",
    description: "Iron fist smashes 1 square!",
    key: "MetalMn V2M",
    chipType: "giga",
  },
  {
    number: 64,
    image: "",
    name: "MetalMn V3",
    type: "",
    damage: "160",
    lettercode: "M",
    memory: "70 MB",
    description: "Iron fist smashes 1 square!",
    key: "MetalMn V3M",
    chipType: "giga",
  },
  {
    number: 65,
    image: "",
    name: "MetalMn V4",
    type: "",
    damage: "190",
    lettercode: "M",
    memory: "80 MB",
    description: "Iron fist smashes 1 square!",
    key: "MetalMn V4M",
    chipType: "giga",
  },
  {
    number: 66,
    image: "",
    name: "KingMan",
    type: "",
    damage: "140",
    lettercode: "K",
    memory: "36 MB",
    description: "Move up 3 square & 4-way hit",
    key: "KingManK",
    chipType: "giga",
  },
  {
    number: 67,
    image: "",
    name: "KingMan V2",
    type: "",
    damage: "170",
    lettercode: "K",
    memory: "48 MB",
    description: "Move up 3 square & 4-way hit",
    key: "KingMan V2K",
    chipType: "giga",
  },
  {
    number: 68,
    image: "",
    name: "KingMan V3",
    type: "",
    damage: "200",
    lettercode: "K",
    memory: "60 MB",
    description: "Move up 3 square & 4-way hit",
    key: "KingMan V3K",
    chipType: "giga",
  },
  {
    number: 69,
    image: "",
    name: "KingMan V4",
    type: "",
    damage: "240",
    lettercode: "K",
    memory: "72 MB",
    description: "Move up 3 square & 4-way hit",
    key: "KingMan V4K",
    chipType: "giga",
  },
  {
    number: 70,
    image: "",
    name: "MistMan",
    type: "",
    damage: "90",
    lettercode: "M",
    memory: "68 MB",
    description: "Appears from mist & attacks",
    key: "MistManM",
    chipType: "giga",
  },
  {
    number: 71,
    image: "",
    name: "MistMan V2",
    type: "",
    damage: "110",
    lettercode: "M",
    memory: "71 MB",
    description: "Appears from mist & attacks",
    key: "MistMan V2M",
    chipType: "giga",
  },
  {
    number: 72,
    image: "",
    name: "MistMan V3",
    type: "",
    damage: "130",
    lettercode: "M",
    memory: "74 MB",
    description: "Appears from mist & attacks",
    key: "MistMan V3M",
    chipType: "giga",
  },
  {
    number: 73,
    image: "",
    name: "MistMan V4",
    type: "",
    damage: "150",
    lettercode: "M",
    memory: "77 MB",
    description: "Appears from mist & attacks",
    key: "MistMan V4M",
    chipType: "giga",
  },
  {
    number: 74,
    image: "",
    name: "BowlMan",
    type: "",
    damage: "100",
    lettercode: "B",
    memory: "80 MB",
    description: "Lines up pins for a strike!",
    key: "BowlManB",
    chipType: "giga",
  },
  {
    number: 75,
    image: "",
    name: "BowlMan V2",
    type: "",
    damage: "120",
    lettercode: "B",
    memory: "82 MB",
    description: "Lines up pins for a strike!",
    key: "BowlMan V2B",
    chipType: "giga",
  },
  {
    number: 76,
    image: "",
    name: "BowlMan V3",
    type: "",
    damage: "140",
    lettercode: "B",
    memory: "84 MB",
    description: "Lines up pins for a strike!",
    key: "BowlMan V3B",
    chipType: "giga",
  },
  {
    number: 77,
    image: "",
    name: "BowlMan V4",
    type: "",
    damage: "160",
    lettercode: "B",
    memory: "86 MB",
    description: "Lines up pins for a strike!",
    key: "BowlMan V4B",
    chipType: "giga",
  },
  {
    number: 78,
    image: "",
    name: "DarkMan",
    type: "",
    damage: "30",
    lettercode: "D",
    memory: "72 MB",
    description: "Creates 3 caves in enmy area",
    key: "DarkManD",
    chipType: "giga",
  },
  {
    number: 79,
    image: "",
    name: "DarkMan V2",
    type: "",
    damage: "30",
    lettercode: "D",
    memory: "76 MB",
    description: "Creates 3 caves in enmy area",
    key: "DarkMan V2D",
    chipType: "giga",
  },
  {
    number: 80,
    image: "",
    name: "DarkMan V3",
    type: "",
    damage: "30",
    lettercode: "D",
    memory: "80 MB",
    description: "Creates 3 caves in enmy area",
    key: "DarkMan V3D",
    chipType: "giga",
  },
  {
    number: 81,
    image: "",
    name: "DarkMan V4",
    type: "",
    damage: "30",
    lettercode: "D",
    memory: "84 MB",
    description: "Creates 3 caves in enmy area",
    key: "DarkMan V4D",
    chipType: "giga",
  },
  {
    number: 82,
    image: "",
    name: "JapanMan",
    type: "",
    damage: "40",
    lettercode: "Y",
    memory: "82 MB",
    description: "Multiple attacks w/ spear",
    key: "JapanManY",
    chipType: "giga",
  },
  {
    number: 83,
    image: "",
    name: "JapanMn V2",
    type: "",
    damage: "45",
    lettercode: "Y",
    memory: "85 MB",
    description: "Multiple attacks w/ spear",
    key: "JapanMn V2Y",
    chipType: "giga",
  },
  {
    number: 84,
    image: "",
    name: "JapanMn V3",
    type: "",
    damage: "50",
    lettercode: "Y",
    memory: "88 MB",
    description: "Multiple attacks w/ spear",
    key: "JapanMn V3Y",
    chipType: "giga",
  },
  {
    number: 85,
    image: "",
    name: "JapanMn V4",
    type: "",
    damage: "55",
    lettercode: "Y",
    memory: "91 MB",
    description: "Multiple attacks w/ spear",
    key: "JapanMn V4Y",
    chipType: "giga",
  },
  {
    number: 86,
    image: "",
    name: "Punk",
    type: "",
    damage: "180",
    lettercode: "P",
    memory: "92 MB",
    description: "Spins and smashes enemies!",
    key: "PunkP",
    chipType: "giga",
  },
];
